export const CODE_EDITOR_DOM_POLICY = Object.freeze({
  tags: ["div", "span", "br", "img", "input", "button", "label", "ul", "li", "style"],
  attributes: {
    class: "^[^<>\"']{0,240}$",
    style: "^[^<>\"']{0,2400}$",
    role: "^(?:textbox|presentation|status|button|listbox|option)$",
    "aria-label": "^[^<>]{0,160}$",
    "aria-live": "^(?:polite|assertive|off)$",
    "aria-hidden": "^(?:true|false)$",
    "aria-selected": "^(?:true|false)$",
    "aria-expanded": "^(?:true|false)$",
    "aria-haspopup": "^listbox$",
    "aria-autocomplete": "^(?:list|none)$",
    "aria-multiline": "^(?:true|false)$",
    "aria-controls": "^[A-Za-z0-9_-]{0,120}$",
    "aria-activedescendant": "^[A-Za-z0-9_-]{0,120}$",
    contenteditable: "^(?:true|false)$",
    tabindex: "^-?\\d+$",
    spellcheck: "^(?:true|false)$",
    writingsuggestions: "^(?:true|false)$",
    autocorrect: "^(?:on|off)$",
    autocapitalize: "^(?:on|off|none)$",
    translate: "^(?:yes|no)$",
    src: "^data:image/gif;base64,[A-Za-z0-9+/=]+$",
    alt: "^[^<>]{0,80}$",
    type: "^(?:text|checkbox|button)$",
    name: "^[A-Za-z0-9_-]{0,80}$",
    value: "^[^<>]{0,500}$",
    id: "^[A-Za-z0-9_-]{1,120}$",
    title: "^[^<>]{0,160}$",
    placeholder: "^[^<>]{0,160}$",
    "data-language": "^(?:javascript)$",
    form: "^$",
    "main-field": "^true$",
  },
  classNames: ["^cm-[A-Za-z0-9_-]+$", "^tok-[A-Za-z0-9_-]+$", "^ͼ[A-Za-z0-9]+$"],
  maxElements: 600,
  maxDepth: 16,
  maxTextLength: 200_000,
});
